from cooker import *

myCooker = cooker("local",True)
#env.hosts=['127.0.0.1']
myCooker.setPackage("yum")
myCooker.connect("127.0.0.1")
#print myCooker.getMode()
#myCooker.dir_ensure("/tmp/tototoot",user="k.sewnundun",group="k.sewnundun",permissions="777",recursive=True)
#myCooker.dir_remove("/tmp/tototoot",True)
#print myCooker.file_diff(["/root/a.php","/root/c.php"])
#print myCooker.dir_getHash("/tmp",algorithm="sha256")
#print myCooker.process_find(["httpd","udevd"])
#print myCooker.process_find("httpd")
#myCooker.process_killByName("rotatelogs")
#myCooker.test()
#myCooker.process_sendSignal("httpd","9")
#print myCooker.process_swapValue("httpd")
#print myCooker.process_swapValue(["httpd","mingetty","toto"])
#print myCooker.process_maps("httpd")
#myCooker.createUser(user="d.dya",password = "toto",home = None,shell = "/bin/sh",group = None,createHome = True )
#myCooker.deleteUser(uid="1113",deleteHome=True)
print myCooker.dir_getRunningProcessUser("/")